"""Add organizations table with industry, employees_count_range, country, currency fields

Revision ID: 3247e9858f90
Revises: 91ec598412dc
Create Date: 2025-11-11 11:10:48.207225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3247e9858f90'
down_revision = '91ec598412dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('organization_code', sa.String(length=8), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('employees_count_range', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_organization_code'), 'organizations', ['organization_code'], unique=True)
    op.create_index(op.f('ix_organizations_organization_name'), 'organizations', ['organization_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_organization_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_organization_code'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
