"""add_geofence_fields_to_organizations

Revision ID: 3fe17be012b5
Revises: e83a9a415f86
Create Date: 2025-11-15 03:47:06.806700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe17be012b5'
down_revision = 'e83a9a415f86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('geofence_latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('organizations', sa.Column('geofence_longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('organizations', sa.Column('geofence_radius', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'geofence_radius')
    op.drop_column('organizations', 'geofence_longitude')
    op.drop_column('organizations', 'geofence_latitude')
    # ### end Alembic commands ###
