"""add_employees_table

Revision ID: 46868b05f34d
Revises: e1e07431d395
Create Date: 2025-11-12 16:35:24.785473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46868b05f34d'
down_revision = 'e1e07431d395'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('work_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', name='worktype'), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'HR_MANAGER', 'STAFF', name='employeerole'), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('shift', sa.String(), nullable=False),
    sa.Column('employee_code', sa.String(length=10), nullable=False),
    sa.Column('qr_code', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_qr_code'), 'employees', ['qr_code'], unique=True)
    op.create_unique_constraint('uq_employee_code_organization', 'employees', ['employee_code', 'organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_code_organization', 'employees', type_='unique')
    op.drop_index(op.f('ix_employees_qr_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
