"""add_payroll_records_table

Revision ID: 5ee65ff3e8f3
Revises: 9d4762e73615
Create Date: 2025-12-01 14:23:06.630066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee65ff3e8f3'
down_revision = '9d4762e73615'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('attendance_days', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', name='payrollstatus'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'period_year', 'period_month', name='uq_payroll_employee_period')
    )
    op.create_index('ix_payroll_period', 'payroll_records', ['organization_id', 'period_year', 'period_month'], unique=False)
    op.create_index(op.f('ix_payroll_records_employee_id'), 'payroll_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_records_id'), 'payroll_records', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_records_organization_id'), 'payroll_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payroll_records_period_month'), 'payroll_records', ['period_month'], unique=False)
    op.create_index(op.f('ix_payroll_records_period_year'), 'payroll_records', ['period_year'], unique=False)
    op.create_index(op.f('ix_payroll_records_status'), 'payroll_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_records_status'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_period_year'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_period_month'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_organization_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_employee_id'), table_name='payroll_records')
    op.drop_index('ix_payroll_period', table_name='payroll_records')
    op.drop_table('payroll_records')
    # ### end Alembic commands ###
