"""Refactor organizations fields (remove subdomain/company_size; add employees_count/country/currency/plan; industry to string)

Revision ID: 5ffe201e0c20
Revises: 82cb94212270
Create Date: 2025-11-06 16:26:17.606041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ffe201e0c20'
down_revision = '82cb94212270'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('employees_count', sa.Integer(), nullable=False))
    op.add_column('organizations', sa.Column('country', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('plan', sa.String(), nullable=True))
    op.alter_column('organizations', 'industry',
               existing_type=postgresql.ENUM('TECHNOLOGY', 'HEALTHCARE', 'FINANCE', 'RETAIL', 'MANUFACTURING', 'EDUCATION', 'OTHER', name='industrytype'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_organizations_subdomain', table_name='organizations')
    op.drop_column('organizations', 'company_size')
    op.drop_column('organizations', 'subdomain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('subdomain', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('company_size', postgresql.ENUM('SIZE_1_10', 'SIZE_11_50', 'SIZE_51_200', 'SIZE_201_500', 'SIZE_501_PLUS', name='companysize'), autoincrement=False, nullable=False))
    op.create_index('ix_organizations_subdomain', 'organizations', ['subdomain'], unique=False)
    op.alter_column('organizations', 'industry',
               existing_type=sa.String(),
               type_=postgresql.ENUM('TECHNOLOGY', 'HEALTHCARE', 'FINANCE', 'RETAIL', 'MANUFACTURING', 'EDUCATION', 'OTHER', name='industrytype'),
               existing_nullable=False)
    op.drop_column('organizations', 'plan')
    op.drop_column('organizations', 'currency')
    op.drop_column('organizations', 'country')
    op.drop_column('organizations', 'employees_count')
    # ### end Alembic commands ###
