"""Add plan field to organizations table

Revision ID: 778538ff446d
Revises: 3247e9858f90
Create Date: 2025-11-11 13:29:31.412790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778538ff446d'
down_revision = '3247e9858f90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('plan', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'plan')
    # ### end Alembic commands ###
