"""Add full_name to users table

Revision ID: 82cb94212270
Revises: 68751d6aeb22
Create Date: 2025-11-06 14:57:21.841679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cb94212270'
down_revision = '68751d6aeb22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    
    # Step 2: Update existing users with a default value
    op.execute("UPDATE users SET full_name = 'Admin User' WHERE full_name IS NULL")
    
    # Step 3: Make the column non-nullable
    op.alter_column('users', 'full_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
