"""add_salary_per_hour_and_optional_dob

Revision ID: 8b7deb91ef2a
Revises: 46868b05f34d
Create Date: 2025-11-13 11:42:11.858913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7deb91ef2a'
down_revision = '46868b05f34d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('salary_per_hour', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('employees', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('employees', 'salary_per_hour')
    # ### end Alembic commands ###
