"""add_session_management_and_hours_worked

Revision ID: e83a9a415f86
Revises: 9dc893119138
Create Date: 2025-11-15 03:27:53.982979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83a9a415f86'
down_revision = '9dc893119138'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employee_sessions_employee_active', 'employee_sessions', ['employee_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_employee_sessions_employee_id'), 'employee_sessions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_sessions_expires_at'), 'employee_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_employee_sessions_id'), 'employee_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_employee_sessions_token_hash'), 'employee_sessions', ['token_hash'], unique=False)
    op.add_column('attendances', sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('attendances', sa.Column('check_in_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_attendances_check_in_id', 'attendances', 'attendances', ['check_in_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_attendances_check_in_id', 'attendances', type_='foreignkey')
    op.drop_column('attendances', 'check_in_id')
    op.drop_column('attendances', 'hours_worked')
    op.drop_index(op.f('ix_employee_sessions_token_hash'), table_name='employee_sessions')
    op.drop_index(op.f('ix_employee_sessions_id'), table_name='employee_sessions')
    op.drop_index(op.f('ix_employee_sessions_expires_at'), table_name='employee_sessions')
    op.drop_index(op.f('ix_employee_sessions_employee_id'), table_name='employee_sessions')
    op.drop_index('ix_employee_sessions_employee_active', table_name='employee_sessions')
    op.drop_table('employee_sessions')
    # ### end Alembic commands ###
